import createClient, { type Middleware } from 'openapi-fetch'
import type { paths } from './openapi-schema' // generated by openapi-typescript cli
import { env } from '$env/dynamic/private'

const authMiddleware: Middleware = {
  async onRequest({ request }) {
    // TODO: Update this middleware to let admin users sign in
    // via cookie auth.
    // To achieve this, some headers need to be forwarded to and from the API.
    request.headers.set('bff_api_key', env.BFF_API_KEY)
  },
}

/**
 * This API client should only be used on the server side, for example in remote functions.
 */
export const client = createClient<paths>({
  baseUrl: env.BACKEND_API_URL,
})

client.use(authMiddleware)
