import createClient from 'openapi-fetch'
import type { paths } from './openapi-schema' // generated by openapi-typescript cli
import { env } from '$env/dynamic/private'

export const client = createClient<paths>({
  baseUrl: env.BACKEND_API_URL,
  headers: new Headers({ bff_api_key: env.BFF_API_KEY }),
})
