name: Run backend tests on PR
on:
  pull_request:
    paths:
      - "**.ts"

permissions:
  pull-requests: read
  actions: write
  contents: read

jobs:
  run-backend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          pnpm install

      - name: Run tests
        working-directory: ./backend
        run: |
          pnpm test
